version: '3.4'

services:
  example.api:
    image: ${DOCKER_REGISTRY-}exampleapi
    build:
      context: .
      dockerfile: Example.Api/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        MSSQL_SA_PASSWORD: "Pa55w0rd2019"
        ACCEPT_EULA: "Y"
    ports: 
      - "1444:1433" 